### ISSUE TITLE
When I run this program, an error appears:

### ISSUE THREAD

**Issue by chensuixin** [sreyas-mohan/DeepFreq#2]
When I run this program, an error appears: UserWarning: Using a target size (torch.Size([256, 1000])) that is different to the input size (torch.Size([256, 1320])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
Looking forward to your reply

**Comment by gizacard** [comment]
The old version of the code works with pytorch <= 1.4.0. The bug comes from changes in the way circular padding works in newer pytorch versions.
I've pushed a fix that should work for different version except pytorch 1.5 and pytorch 1.6 with even kernel size (which we are not using by default).
